### ISSUE TITLE
New release 2.3.0 didn't make it to the releases page

### ISSUE THREAD

**Issue by smainz** [jackc/tern#114]
Hi @jackc,

the commit [Release v2.3.0](https://github.com/jackc/tern/commit/504c4159b208a186fb88ba5efb375fff3a15d6f7) did not make it to the [releases page](https://github.com/jackc/tern/releases).

Would you be so kind ...

**Comment by jackc** [comment]
Sorry, made the commit but forgot to make the tag. Done.

**Comment by smainz** [comment]
Looks like I broke it.
It can't find the WindowsSSHAgent during the build. It is neigther windows nor (not windows).

I will do some tests tomorrow.

**Comment by smainz** [comment]
Probably we have to add `win_ssh_agent_other.go` and  `win_ssh_agent_windows.go` into `.goreleaser.yaml` like this:


```yaml
dockers:
  - image_templates:
    - &amd_image 'ghcr.io/jackc/tern:{{ .Tag }}-amd64'
    use: buildx
    build_flag_templates:
    - "--push"
    - "--platform=linux/amd64"
    goarch: amd64
    extra_files:
      - go.mod
      - go.sum
      - copy_dir.go
      - main.go
      - ssh_tunnel.go
      - migrate
      - win_ssh_agent_other.go
      - win_ssh_agent_windows.go
```

two times. The normal executables did build, but not the docker images.
