### ISSUE TITLE
port ignored in tern.conf

### ISSUE THREAD

**Issue by sobafuchs** [jackc/tern#63]
System: macOS Monterey version 12.4
tern version: 1.13.0
---

I'm currently facing a weird issue where `port` is being ignored in `tern.conf`. I specified it to be `9200` and `tern` still uses 5432. I have a `docker-compose` file that looks like this:

```yaml
version: "3"
services:
  db:
    container_name: postgres
    restart: always
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tern_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "9200:5432"
volumes:
  postgres_data:
```

I started this up in a separate terminal with `docker-compose up`, I can confirm the pg server is up and running and listening for connections. I then have the following `tern.conf`:

```toml
[database]
host = 127.0.0.1
port = 9200
database = tern_test
user = postgres
password = {{env "MIGRATOR_PASSWORD"}}
sslmode = prefer
```

When I run `tern` with `MIGRATOR_PASSWORD=postgres tern migrate`, I get the following error:

```
Unable to connect to PostgreSQL:
  failed to connect to `host=127.0.0.1 user=postgres database=tern_test`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)
```

If I change my `docker-compose.yml` to expose it on local port 5432, it works of course. I've also tried other ports and it only uses 5432. I'm using macOS Monterey version 12.4 (I saw another issue here specific to Windows, not sure if the OS is even relevant here).
